#!/bin/bash

MQTTSETTING="$2"  #mqtt setting  
echo "${MQTTSETTING}" 
ZONE="$1"    # enviroment Canada rss zone
#ZONE="nb2_e.xml"

prev="$(cat prev)"
OUTPUT="$(curl -s  https://weather.gc.ca/rss/battleboard/${ZONE}.xml | sed -n 's:.*<title>\(.*\)</title>.*:\1:p' | sed  '1d' | sed  's/in effect//gI' | sed  's/ended//gI' | cut -d',' -f1 | awk '!seen[$1,$2]++' )"
#awk '!seen[$1,$2]++'
#tail -n1
echo "${OUTPUT}"
NO_WHITESPACE="$(echo -e "${OUTPUT}" | tr -d '[:space:]')"

if [ $NO_WHITESPACE == 'Noalerts' ]
   then
     if [ $prev == 'Noalerts'  ]
     then
         echo " "
     else
          echo 'cmd_9(clear)' > /dev/ttyS2  #send command to serial to display on local TFT screen
          mosquitto_pub -h $MQTTSETTING -t '/ai/clear' -m '1' #sends command to remote wifi connected TFT screen
     fi
       echo "${NO_WHITESPACE}" > prev
       echo  all is good
elif [ $NO_WHITESPACE == 'FROSTADVISORY' ]   #silent Alarm just display warning on TFT Screen
     then
     echo 'cmd_5(Frost Warning)' > /dev/ttyS2
     mosquitto_pub -h $MQTTSETTING -t '/ai/clear' -m '1'
     mosquitto_pub -h $MQTTSETTING -t '/ai/station' -m '   Frost Advisory'
     echo  "frost warning"
     echo "${NO_WHITESPACE}" > prev

elif [ $NO_WHITESPACE == 'RAINFALLWARNING' ]   #silent Alarm just display warning on TFT Screen
     then
     echo 'cmd_5($OUTPUT)' > /dev/ttyS2
     mosquitto_pub -h $MQTTSETTING -t '/ai/clear' -m '1'
     mosquitto_pub -h $MQTTSETTING -t '/ai/station' -m "Weather Alert"
     mosquitto_pub -h $MQTTSETTING -t '/ai/artist' -m "${OUTPUT}"
     mosquitto_pub -h $MQTTSETTING -t '/ai/song' -m 'Significant Rainfall Possible                   ... More then 50mm of rain expected'
     #echo  ${OUTPUT}
     echo "${NO_WHITESPACE}" > prev
     mpg123 skills/Evcan-alerts-skill/rain.mp3
     

elif [ $NO_WHITESPACE == 'SPECIALAIRQUALITYSTATEMENT' ]   #silent Alarm just display warning on TFT Screen
     then
     echo 'cmd_5($OUTPUT)' > /dev/ttyS2
     mosquitto_pub -h $MQTTSETTING -t '/ai/clear' -m '1'
     mosquitto_pub -h $MQTTSETTING -t '/ai/station' -m "Weather Statement"
     mosquitto_pub -h $MQTTSETTING -t '/ai/artist' -m "Low Air quality"
     #echo  ${OUTPUT}
     echo "${NO_WHITESPACE}" > prev

elif [ $NO_WHITESPACE == 'SPECIALWEATHERSTATEMENT' ]   #silent Alarm just display warning on $
     then
     echo 'cmd_5($OUTPUT)' > /dev/ttyS2
     mosquitto_pub -h $MQTTSETTING -t '/ai/clear' -m '1'
     mosquitto_pub -h $MQTTSETTING -t '/ai/station' -m "Weather Statement"
     mosquitto_pub -h $MQTTSETTING -t '/ai/artist' -m "Strong System Developing"
     mosquitto_pub -h $MQTTSETTING -t '/ai/song' -m 'High precip &/or Winds Possible          ...... '
     #echo  ${OUTPUT}
     echo "${NO_WHITESPACE}" > prev

elif [ $NO_WHITESPACE == 'SNOWFALLWARNING' ]   #silent Alarm just display warning on TFT Screen
     then
     echo 'cmd_5($OUTPUT)' > /dev/ttyS2
     mosquitto_pub -h $MQTTSETTING -t '/ai/clear' -m '1'
     mosquitto_pub -h $MQTTSETTING -t '/ai/station' -m "Weather Alert"
     mosquitto_pub -h $MQTTSETTING -t '/ai/artist' -m "${OUTPUT}"
     mosquitto_pub -h $MQTTSETTING -t '/ai/song' -m 'Significant Snowfall Expected'
     echo "${NO_WHITESPACE}" > prev
     mpg123 skills/Evcan-alerts-skill/bleep.mp3

elif [ $NO_WHITESPACE == 'WEATHERADVISORY' ]   #silent Alarm just display warning on TFT Screen
     then
     echo 'cmd_5($OUTPUT)' > /dev/ttyS2
     mosquitto_pub -h $MQTTSETTING -t '/ai/clear' -m '1'
     mosquitto_pub -h $MQTTSETTING -t '/ai/station' -m "Weather Advisory"
     mosquitto_pub -h $MQTTSETTING -t '/ai/artist' -m "Intense System developing"
     mosquitto_pub -h $MQTTSETTING -t '/ai/song' -m 'Low Pressure Cell - Lighting, Hail          ... &/or Strong Winds could Develop '
     echo "${NO_WHITESPACE}" > prev

elif [ $NO_WHITESPACE == 'HEATWARNING' ]   #silent Alarm just display warning on TFT Screen
     then
     echo 'cmd_5($OUTPUT)' > /dev/ttyS2
     mosquitto_pub -h $MQTTSETTING -t '/ai/clear' -m '1'
     mosquitto_pub -h $MQTTSETTING -t '/ai/station' -m "Weather Alert"
     mosquitto_pub -h $MQTTSETTING -t '/ai/artist' -m "Heat Warning"
     mosquitto_pub -h $MQTTSETTING -t '/ai/song' -m ' High tempertures &/or High humidity'
     echo "${NO_WHITESPACE}" > prev

elif [ $NO_WHITESPACE == 'SEVERETHUNDERSTORMWARNING' ]   #silent Alarm just display warning on TFT Screen
     then
     echo 'cmd_5($OUTPUT)' > /dev/ttyS2
     mosquitto_pub -h $MQTTSETTING -t '/ai/clear' -m '1'
     mosquitto_pub -h $MQTTSETTING -t '/ai/station' -m "Weather Alert"
     mosquitto_pub -h $MQTTSETTING -t '/ai/artist' -m "Severe ThunderStorm"
     mosquitto_pub -h $MQTTSETTING -t '/ai/song' -m 'Possible sever ThunderStorm'
     echo "${NO_WHITESPACE}" > prev
     mpg123 skills/Evcan-alerts-skill/thunder.mp3
     
elif [ $NO_WHITESPACE == 'SEVERETHUNDERSTORMWATCH' ]   #silent Alarm just display warning on TFT Screen
     then
     echo 'cmd_5($OUTPUT)' > /dev/ttyS2
     mosquitto_pub -h $MQTTSETTING -t '/ai/clear' -m '1'
     mosquitto_pub -h $MQTTSETTING -t '/ai/station' -m "Weather Watch"
     mosquitto_pub -h $MQTTSETTING -t '/ai/artist' -m "Severe ThunderStorm"
     mosquitto_pub -h $MQTTSETTING -t '/ai/song' -m 'Possible sever ThunderStorm'
     echo "${NO_WHITESPACE}" > prev  
     mpg123 skills/Evcan-alerts-skill/thunder.mp3 

else                                       # full alarm   speech and display
    /$HOME/mycroft-core/bin/mycroft-say-to stop
    mpg123 skills/Evcan-alerts-skill/Alarm.mpg
    #echo 'cmd_5(Weather Alert)' > /dev/ttyS2
    mosquitto_pub -h $MQTTSETTING -t '/ai/station' -m 'Weather Alert'
    #echo 'cmd_6($OUTPUT)' > /dev/ttyS2
    mosquitto_pub -h $MQTTSETTING -t '/ai/artist' -m "${OUTPUT}"
    /$HOME/mycroft-core/bin/mycroft-speak  weather alert     ${OUTPUT}

fi
